name: ci-cd
run-name: Build article-improver 🚀

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'
    - name: Install Hatch
      run: |
        python -m pip install --upgrade pip 
        pip install hatch
    - name: Run tests
      run: hatch run test
  build:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'
    - name: Install Hatch
      run: |
        python -m pip install --upgrade pip 
        pip install hatch
    - name: Build package
      run: hatch build
    - uses: actions/upload-artifact@v4
      with:
        name: article-improver-dist
        path: dist/*
  release:
    runs-on: ubuntu-latest
    needs: [build]
    if: startsWith(github.ref, 'refs/tags/')
    steps:
    - uses: actions/checkout@v3
    - uses: actions/download-artifact@v4
      with:
        name: article-improver-dist
        path: article-improver-dist
    - name: Generate Changelog
      run: |
        echo "# article-improver release 🚀" > ${{ github.workspace }}-CHANGELOG.txt
        echo "" >> ${{ github.workspace }}-CHANGELOG.txt
        echo "Test release for Medium article" >> ${{ github.workspace }}-CHANGELOG.txt
        echo "" >> ${{ github.workspace }}-CHANGELOG.txt
        echo "- Follow me on [Medium](https://vitalii-honchar.medium.com/) 🔥" >> ${{ github.workspace }}-CHANGELOG.txt
        echo "- Connect with me on [LinkedIn](https://www.linkedin.com/in/vitaliihonchar/) 😎" >> ${{ github.workspace }}-CHANGELOG.txt
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        body_path: ${{ github.workspace }}-CHANGELOG.txt
        files: article-improver-dist/*